Update submitty_ci.yml

diff --git a/.github/workflows/submitty_ci.yml b/.github/workflows/submitty_ci.yml
--- a/.github/workflows/submitty_ci.yml
+++ b/.github/workflows/submitty_ci.yml
@@ -405,7 +405,6 @@ jobs:
               sudo rm -rf /etc/apache2/sites-enabled/*
               sudo cp -f .setup/apache/submitty.conf /etc/apache2/sites-available/submitty.conf
               sudo sed -e "s/Require host __your_domain__/Require all granted/g" --in-place /etc/apache2/sites-available/submitty.conf
-              sudo sed -e "s/:80/:443/g" --in-place /etc/apache2/sites-available/submitty.conf
               sudo cp .setup/apache/www-data /etc/apache2/suexec/www-data
               sudo chmod 0640 /etc/apache2/suexec/www-data
               sudo a2ensite submitty
@@ -431,11 +430,13 @@ jobs:
             run: |
               cd $SUBMITTY_REPOSITORY
               if [ -f .setup/dev-upgrade-h2.sh ]; then
+                sudo sed -e "s/:80/:443/g" --in-place /etc/apache2/sites-available/submitty.conf
                 sudo -E env "PATH=$PATH" bash .setup/dev-upgrade-h2.sh up --i-know-what-i-am-doing-please-go-ahead \
                   && echo "HTTP_PROTO=https" >> $GITHUB_ENV                                                        \
-                  || echo "HTTP_PROTO=http"  >> $GITHUB_ENV  # Note that we assume the above command always success
+                  || echo "HTTP_PROTO=http"  >> $GITHUB_ENV     # Note that we assume the echo above is always true
               else
                 echo "HTTP_PROTO=http" >> $GITHUB_ENV
+                echo "Cannot find .setup/dev-upgrade-h2.sh, keep HTTP"
               fi
 
           - name: Run git tests
